# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-21 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0017_auto_20170421_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='name',
        ),
        migrations.AddField(
            model_name='sla',
            name='title',
            field=models.CharField(default=2, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
